add_rules("mode.debug", "mode.release")
add_requires("opencv")
target("tag")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("opencv")
    after_build(function (target)
        os.cp("assets", target:targetdir())
    end)